-- Create tasks table
CREATE TABLE tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  phase TEXT NOT NULL,
  phase_order INT NOT NULL,
  task_order INT NOT NULL,
  text TEXT NOT NULL,
  category TEXT NOT NULL,
  notes TEXT,
  completed BOOLEAN DEFAULT FALSE,
  completed_by UUID REFERENCES auth.users(id),
  completed_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Create policy
CREATE POLICY "Users can read and update all tasks" ON tasks FOR ALL USING (auth.role() = 'authenticated');

-- Seed data
INSERT INTO tasks (phase, phase_order, task_order, text, category, notes) VALUES
('Phase 1: Foundation', 1, 1, 'Set overall wedding budget with Hannah (total $ ceiling + rough category splits)', 'Budget', 'Ballroom weddings in Chicago for ~80 typically run $85K–$200K+.'),
('Phase 1: Foundation', 1, 2, 'Clarify who''s contributing financially and have the conversations', 'Budget', 'Do this before setting the budget number so expectations align.'),
('Phase 1: Foundation', 1, 3, 'Draft preliminary guest list with Hannah to confirm ~80 count (A-list + B-list)', 'Guest List', 'B-list = invited only if A-list declines. Keeps total manageable.'),
('Phase 1: Foundation', 1, 4, 'Decide on wedding weekend window (Fri/Sat/Sun in mid-to-late May 2027)', 'Venue', 'May 14–16, 21–23, 28–30. Memorial Day weekend has pros and cons.'),
('Phase 1: Foundation', 1, 5, 'Tour The LaSalle, Langham Chelsea, CAA (Madison + Cindy''s), and 1–2 dark horses', 'Venue', 'Ask about: included rentals, F&B minimums, corkage, vendor restrictions, overtime fees, getting-ready suites.'),
('Phase 1: Foundation', 1, 6, 'Decide: full-service planner, partial planner, or month-of coordinator', 'Planning', 'For hands-on couples, partial planner hired ~9 months out is the common sweet spot.'),
('Phase 1: Foundation', 1, 7, 'Interview 2–3 planners/coordinators if going that route', 'Planning', 'Ask for references from weddings at your venue shortlist.'),
('Phase 1: Foundation', 1, 8, 'Book venue + sign contract + pay deposit', 'Venue', 'This locks the date. Everything downstream depends on it.'),
('Phase 1: Foundation', 1, 9, 'Start Pinterest + shared inspiration folder (romantic garden vibe)', 'Design', 'Separate boards: ceremony, reception, florals, attire, details.'),
('Phase 1: Foundation', 1, 10, 'Decide on getting-ready location (hotel suite, venue suite, Airbnb, home)', 'Venue', 'Factor in photo quality of the space — morning light matters.'),
('Phase 1: Foundation', 1, 11, 'Talk through ceremony style: religious, secular, interfaith, officiant type', 'Ceremony', 'If religious, this affects venue + timeline significantly.'),
('Phase 2: Core Vendors', 2, 1, 'Book photographer', 'Photo/Video', 'Top Chicago wedding photographers book 12–15 months out. Romantic garden → look for film or film-hybrid.'),
('Phase 2: Core Vendors', 2, 2, 'Book videographer', 'Photo/Video', 'Decide: cinematic highlight, documentary, or both. Often same studio bundles.'),
('Phase 2: Core Vendors', 2, 3, 'Book florist / floral designer', 'Florals', 'For garden/abundant florals, interview designers who specialize in this look specifically.'),
('Phase 2: Core Vendors', 2, 4, 'Book band or DJ', 'Music', 'Decide band vs DJ vs hybrid. Bands book earlier. Live ceremony music is a separate booking.'),
('Phase 2: Core Vendors', 2, 5, 'Book officiant (if not using venue/religious)', 'Ceremony', 'If using a friend, they''ll need to get ordained + registered.'),
('Phase 2: Core Vendors', 2, 6, 'Choose wedding planner/coordinator and sign contract', 'Planning', ''),
('Phase 2: Core Vendors', 2, 7, 'Confirm venue catering OR book external caterer', 'Catering', 'The LaSalle has in-house catering — confirm menu tasting timing.'),
('Phase 2: Core Vendors', 2, 8, 'Start engagement shoot planning (most photographers include one)', 'Photo/Video', 'Doubles as save-the-date photos.'),
('Phase 2: Core Vendors', 2, 9, 'Decide on wedding website platform', 'Communications', 'Withjoy is popular with design-forward couples. Zola is most full-featured.'),
('Phase 2: Core Vendors', 2, 10, 'Build wedding website skeleton', 'Communications', ''),
('Phase 2: Core Vendors', 2, 11, 'Decide on wedding party composition (Bubba as ring bearer?)', 'Wedding Party', ''),
('Phase 2: Core Vendors', 2, 12, 'Ask wedding party — they plan travel + outfits around this', 'Wedding Party', 'Consider a cute ask: small gift, handwritten note, or photo opportunity.'),
('Phase 3: Design & Logistics', 3, 1, 'Finalize color palette (dusty romance vs fresh garden vs moody garden)', 'Design', 'Commit before ordering stationery, linens, or bridesmaid dresses.'),
('Phase 3: Design & Logistics', 3, 2, 'Design + order save-the-dates (send 6–8 months before = Nov–Dec 2026)', 'Stationery', 'Send earlier for destination or holiday-adjacent dates.'),
('Phase 3: Design & Logistics', 3, 3, 'Finalize STD guest list + gather all mailing addresses', 'Guest List', 'Single spreadsheet: name, address, email, RSVP, meal, +1, table. This is your master.'),
('Phase 3: Design & Logistics', 3, 4, 'Send save-the-dates', 'Stationery', ''),
('Phase 3: Design & Logistics', 3, 5, 'Hannah shops for + orders wedding dress', 'Attire', 'Bridal gowns take 6–9 months + alterations. Don''t wait past Oct 2026.'),
('Phase 3: Design & Logistics', 3, 6, 'Ryan shops for tuxedo/suit (custom takes 3–4 months)', 'Attire', 'Chicago options: Bespoke Chicago, Formally Modern Tuxedo, or personal tailor.'),
('Phase 3: Design & Logistics', 3, 7, 'Book hair + makeup artist (trial included in most packages)', 'Beauty', ''),
('Phase 3: Design & Logistics', 3, 8, 'Book transportation (getting-ready → venue, shuttles)', 'Logistics', ''),
('Phase 3: Design & Logistics', 3, 9, 'Reserve hotel blocks (2 tiers: nicer + more affordable)', 'Logistics', 'Blocks need 10+ rooms. The LaSalle is in the Loop — many options.'),
('Phase 3: Design & Logistics', 3, 10, 'Create registry (home goods, experiences, honeymoon fund)', 'Registry', 'Zola lets you mix all three.'),
('Phase 3: Design & Logistics', 3, 11, 'Book rehearsal dinner venue', 'Events', 'Often hosted by groom''s parents. Night before the wedding.'),
('Phase 3: Design & Logistics', 3, 12, 'Research + book honeymoon (or at least lock destination)', 'Honeymoon', 'Ideal windows: June 2027 or early fall 2027.'),
('Phase 3: Design & Logistics', 3, 13, 'Start skincare / fitness / wellness protocol', 'Personal', ''),
('Phase 3: Design & Logistics', 3, 14, 'Book pre-wedding events: shower, engagement party, bach/bach', 'Events', 'Bach/bach parties typically 2–4 months before wedding.'),
('Phase 4: Details & Decisions', 4, 1, 'Finalize floral design — arch, centerpieces, aisle, bouquets, installations', 'Florals', 'Splurge call: one big floral moment (ceremony installation or head table).'),
('Phase 4: Details & Decisions', 4, 2, 'Order invitation suite (invite, RSVP, details, envelopes, calligraphy)', 'Stationery', 'Send invites 8–10 weeks out = mid-March 2027. Calligraphy adds ~4 weeks.'),
('Phase 4: Details & Decisions', 4, 3, 'Decide on day-of paper: menus, place cards, escorts, programs, signage', 'Stationery', 'Order with invitations for design consistency.'),
('Phase 4: Details & Decisions', 4, 4, 'Menu tasting with caterer / venue', 'Catering', 'Ask about: dietary restrictions, kids meals, late-night snacks.'),
('Phase 4: Details & Decisions', 4, 5, 'Finalize bar package (open bar, signature cocktails, wine)', 'Catering', 'Signature cocktail with edible flower or herb is a cute garden touch.'),
('Phase 4: Details & Decisions', 4, 6, 'Book rentals: linens, chairs, glassware, chargers, napkins', 'Rentals', 'Chicago go-tos: Hall''s Rental Service, BBJ La Tavola.'),
('Phase 4: Details & Decisions', 4, 7, 'Book lighting designer or add lighting to rental order', 'Rentals', 'Market lights, uplighting, candles. High-ROI spend.'),
('Phase 4: Details & Decisions', 4, 8, 'Hannah: first dress fitting', 'Attire', ''),
('Phase 4: Details & Decisions', 4, 9, 'Book photo booth or guest entertainment (optional)', 'Entertainment', ''),
('Phase 4: Details & Decisions', 4, 10, 'Finalize cake / dessert (baker tasting)', 'Catering', ''),
('Phase 4: Details & Decisions', 4, 11, 'Plan ceremony: vows, readings, readers, processional, music', 'Ceremony', ''),
('Phase 4: Details & Decisions', 4, 12, 'Meet with officiant to plan ceremony structure', 'Ceremony', ''),
('Phase 4: Details & Decisions', 4, 13, 'Apply for Cook County marriage license (2–4 weeks before)', 'Legal', 'Valid for 60 days from issue — don''t do this too early.'),
('Phase 4: Details & Decisions', 4, 14, 'Finalize bridal party attire + confirm everyone has ordered', 'Attire', ''),
('Phase 4: Details & Decisions', 4, 15, 'Plan wedding party gifts', 'Wedding Party', ''),
('Phase 4: Details & Decisions', 4, 16, 'Plan partner gifts (morning-of exchange)', 'Personal', ''),
('Phase 5: Home Stretch', 5, 1, 'Send invitations (target mid-March 2027)', 'Stationery', 'RSVP deadline = ~3 weeks before wedding.'),
('Phase 5: Home Stretch', 5, 2, 'Finalize honeymoon itinerary, book flights + hotels, passports/visas', 'Honeymoon', ''),
('Phase 5: Home Stretch', 5, 3, 'Hair + makeup trial', 'Beauty', ''),
('Phase 5: Home Stretch', 5, 4, 'Second dress fitting', 'Attire', ''),
('Phase 5: Home Stretch', 5, 5, 'Groom suit fitting', 'Attire', ''),
('Phase 5: Home Stretch', 5, 6, 'Confirm all vendor contracts, payment schedules, arrival times', 'Vendors', 'Build vendor contact sheet: name, role, arrival, phone, balance due.'),
('Phase 5: Home Stretch', 5, 7, 'Create day-of timeline (distribute to vendors + wedding party)', 'Planning', 'Hour-by-hour from getting-ready through last shuttle.'),
('Phase 5: Home Stretch', 5, 8, 'Bachelor + bachelorette parties (late March / early April)', 'Events', ''),
('Phase 5: Home Stretch', 5, 9, 'Bridal shower (usually 2 months out)', 'Events', ''),
('Phase 5: Home Stretch', 5, 10, 'Finalize seating chart (as RSVPs come in)', 'Guest List', 'Tools: Prismm, AllSeated, or an Excel grid.'),
('Phase 5: Home Stretch', 5, 11, 'Write welcome note / welcome bag for out-of-town guests', 'Logistics', ''),
('Phase 5: Home Stretch', 5, 12, 'Write vows (separately, don''t share until the day)', 'Ceremony', ''),
('Phase 5: Home Stretch', 5, 13, 'Prep toast notes — gently remind parents, best man, MOH', 'Ceremony', ''),
('Phase 5: Home Stretch', 5, 14, 'Order wedding bands if not already done', 'Attire', 'Hannah''s band should complement the engagement ring setting.'),
('Phase 5: Home Stretch', 5, 15, 'Figure out Bubba''s weekend plan (sitter, family, cameo)', 'Personal', ''),
('Phase 6: Final 2 Weeks', 6, 1, 'Chase any missing RSVPs', 'Guest List', ''),
('Phase 6: Final 2 Weeks', 6, 2, 'Give final guest count + meal selections to caterer/venue', 'Catering', ''),
('Phase 6: Final 2 Weeks', 6, 3, 'Final seating chart to printer/calligrapher', 'Stationery', ''),
('Phase 6: Final 2 Weeks', 6, 4, 'Final walkthrough at venue with planner + vendors', 'Venue', ''),
('Phase 6: Final 2 Weeks', 6, 5, 'Confirm hair + makeup call times for bridal party', 'Beauty', ''),
('Phase 6: Final 2 Weeks', 6, 6, 'Pre-pay vendors + prepare tip envelopes (labeled, cash)', 'Budget', 'Tips: photo/video ~optional or $100–$300; catering ~15–20%; DJ/band $50–$100/musician; H&M ~15–20%; transport ~15–20%.'),
('Phase 6: Final 2 Weeks', 6, 7, 'Pack emergency kit (sewing kit, stain pen, Tylenol, mints)', 'Logistics', ''),
('Phase 6: Final 2 Weeks', 6, 8, 'Pick up marriage license', 'Legal', ''),
('Phase 6: Final 2 Weeks', 6, 9, 'Confirm welcome bags delivered to hotel', 'Logistics', ''),
('Phase 6: Final 2 Weeks', 6, 10, 'Break in wedding shoes', 'Attire', ''),
('Phase 6: Final 2 Weeks', 6, 11, 'Final dress + suit fitting (steaming, pressing)', 'Attire', ''),
('Phase 6: Final 2 Weeks', 6, 12, 'Write thank-you notes for pre-event hosts', 'Personal', ''),
('Phase 6: Final 2 Weeks', 6, 13, 'Pack honeymoon bags', 'Honeymoon', ''),
('Phase 7: Wedding Week & Day-Of', 7, 1, 'Rehearsal + rehearsal dinner', 'Events', ''),
('Phase 7: Wedding Week & Day-Of', 7, 2, 'Bring items to venue: vows, bands, license, place cards, programs', 'Logistics', ''),
('Phase 7: Wedding Week & Day-Of', 7, 3, 'Hand off all day-of coordination to planner/coordinator', 'Planning', ''),
('Phase 7: Wedding Week & Day-Of', 7, 4, 'Get ready with wedding party', 'Beauty', ''),
('Phase 7: Wedding Week & Day-Of', 7, 5, 'First look or first-see moment (if doing one)', 'Photo/Video', ''),
('Phase 7: Wedding Week & Day-Of', 7, 6, 'Ceremony', 'Ceremony', ''),
('Phase 7: Wedding Week & Day-Of', 7, 7, 'Cocktail hour, reception, dances, toasts, cake, send-off', 'Events', ''),
('Phase 7: Wedding Week & Day-Of', 7, 8, 'Delegate: someone brings gifts back, someone takes attire for cleaning', 'Logistics', ''),
('Phase 8: Post-Wedding', 8, 1, 'Leave for honeymoon', 'Honeymoon', ''),
('Phase 8: Post-Wedding', 8, 2, 'Return rentals (suit, shoes, any linens)', 'Logistics', ''),
('Phase 8: Post-Wedding', 8, 3, 'Preserve or clean wedding dress', 'Attire', ''),
('Phase 8: Post-Wedding', 8, 4, 'File marriage license / obtain certified copies', 'Legal', 'Needed for name change + joint accounts.'),
('Phase 8: Post-Wedding', 8, 5, 'Write + send thank-you notes (within ~3 months)', 'Communications', ''),
('Phase 8: Post-Wedding', 8, 6, 'Name change paperwork (SSA, DMV, passport, bank)', 'Legal', ''),
('Phase 8: Post-Wedding', 8, 7, 'Order photo album + share galleries with family', 'Photo/Video', ''),
('Phase 8: Post-Wedding', 8, 8, 'Review exceptional vendors — it really helps them', 'Vendors', '');

-- Shared notes table
CREATE TABLE shared_notes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  text TEXT,
  updated_by UUID REFERENCES auth.users(id),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO shared_notes (text) VALUES ('');

